/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  84532: {
    Onigo: {
      address: "0x95240d08ee46850c404514654a451f2c8d6f8688",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_broker",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdc",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "broker",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claimPlayerPayout",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createMarket",
          inputs: [
            {
              name: "_marketName",
              type: "string",
              internalType: "string",
            },
            {
              name: "_dataPower",
              type: "int8",
              internalType: "int8",
            },
            {
              name: "_dataIncrement",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "_timeSlotWidth",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "_roundLength",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "houseCommissionBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "markets",
          inputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          outputs: [
            {
              name: "commissionBps",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "dataPower",
              type: "int8",
              internalType: "int8",
            },
            {
              name: "marketId",
              type: "uint16",
              internalType: "uint16",
            },
            {
              name: "dataIncrement",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "timeSlotWidth",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "marketStartTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "roundLength",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "marketName",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "numMarkets",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setBroker",
          inputs: [
            {
              name: "_broker",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleRound",
          inputs: [
            {
              name: "marketId",
              type: "uint16",
              internalType: "uint16",
            },
            {
              name: "roundId",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "_winningCells",
              type: "tuple[]",
              internalType: "struct Onigo.GridCell[]",
              components: [
                {
                  name: "timeSlotStart",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "dataRangeStart",
                  type: "int256",
                  internalType: "int256",
                },
              ],
            },
            {
              name: "players",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "payouts",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unclaimedCommissions",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "unclaimedPlayerPayouts",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawCommissions",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CommissionWithdrawn",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MarketCreated",
          inputs: [
            {
              name: "marketId",
              type: "uint16",
              indexed: true,
              internalType: "uint16",
            },
            {
              name: "marketName",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "marketStartTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "roundLength",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerPayoutClaimed",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RoundSettled",
          inputs: [
            {
              name: "marketId",
              type: "uint16",
              indexed: true,
              internalType: "uint16",
            },
            {
              name: "roundId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "payout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InvalidMarketId",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPlayerBetData",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRoundId",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSettlementData",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidWinningCells",
          inputs: [],
        },
        {
          type: "error",
          name: "NoAmountToClaim",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "RoundSettledAlready",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 37221323,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
